-- Mod Tunings.
TUNING.KYNO_FIREBUFF_DURATION = 480 / 2

TUNING.KYNO_FREEZEBUFF_DURATION = 480 / 2
TUNING.KYNO_FREEZEBUFF_FREEZING = .50

TUNING.KYNO_PRESERVERBUFF_DURATION = 960
TUNING.KYNO_PRESERVERBUFF_RATE = .90
TUNING.KYNO_PRESERVERBUFF_PERISHTIME = 2.5 -- 30000 lol don't do it again. Powdercake had "1687499679" days spoil time.

TUNING.SPICE_MULTIPLIERS =
{
	SPICE_SALT = { HEALTH = .25 },
	SPICE_FED  = { HUNGER = .25 },
	SPICE_MIND = { SANITY = .25 },
}